spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled : true
      routes:
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**


server:
  port: 8222